int _putchar(char c);
int print_alphabet(void);
void print_alphabet_x10(void);
int _isalpha(int c);
int print_sign(int n);
int _abs(int n);
int print_last_digit(int n);
void jack_bauer(void);
void times_table(void);
int add(int num1, int num2);
void print_times_table(int n);
void print_to_98(int n);
